function output = getRotationalProjCompare
%% OVERVIEW

% This function finds the projection of the data into the "jPCA rotational
% plane" using jPCA, along with the reconstruction due to rotations. The
% function then finds the variance in each rotational plane. This function
% compares the R2 between all conditions, straight reaches, and curved. 
%% Find the rotational projection.

% Load the data.
load('TBFResults');

% Loop through and find the planes.
for monkey = 1:size(TBFResults,2)
    [~,~,~,output(monkey).M1.R2s] ...
        = getRotations(TBFResults(monkey).M1.loadings, ...
        TBFResults(monkey).M1.basisFxns,2);
    [~,~,~,output(monkey).M1.R2sStraight] ...
        = getRotations(TBFResults(monkey).M1.loadings(1:2:end), ...
        TBFResults(monkey).M1.basisFxns,2);
    [~,~,~,output(monkey).M1.R2sCurved] ...
        = getRotations(TBFResults(monkey).M1.loadings(2:2:end), ...
        TBFResults(monkey).M1.basisFxns,2);
    [~,~,~,output(monkey).PMd.R2s] ...
        = getRotations(TBFResults(monkey).PMd.loadings, ...
        TBFResults(monkey).PMd.basisFxns,2);
    [~,~,~,output(monkey).PMd.R2sStraight] ...
        = getRotations(TBFResults(monkey).PMd.loadings(1:2:end), ...
        TBFResults(monkey).PMd.basisFxns,2);
    [~,~,~,output(monkey).PMd.R2sCurved] ...
        = getRotations(TBFResults(monkey).PMd.loadings(2:2:end), ...
        TBFResults(monkey).PMd.basisFxns,2);
end

end