function output = kinFromTBFSingleTrial
%% OVERVIEW

% This function uses neural data to predict kinematics from single trial
% spiking. This is done both using linear regression and nonlinear
% kernel regression. Prediction is bottle-necked through the loading
% matrices for temporal basis factorization, meaning that the orientation
% and initial state of dynamics is related to the movement performed. 

%% Parameters.

% Declare the kernel used for non-linear mapping.
kernelType = 'OU';

% Declares the length scale of the kernel.
kernelScale = 10^3;

% Declare the regularization on the kernel for nonlinear mapping.
nonlinearL2 = 10^-5;

% Declare the dimensionality for decoding.
decodeDim = 20;

% Declare the regularization on the linear mapping.
linearL2 = 10;

% Declare the train-test ratio.
holdOutNum = 2;

%% Form the mapping.

% Load the data.
load('ShenoyMonkeyData');
ShenoyMonkeyData = ShenoyMonkeyData(1:2);
load('ShenoyMonkeyDataSingleTrial');
load('basisFxnNum');

% For each monkey and brain region, prepare for analysis.
for monkey = 1:size(ShenoyMonkeyData,2)
    % M1.
    output(monkey).M1 = prepForAnalysis(ShenoyMonkeyData(monkey).M1, ...
        ShenoyMonkeyDataSingleTrial(monkey).M1, ...
        ShenoyMonkeyData(monkey).Kinematics, ...
        ShenoyMonkeyDataSingleTrial(monkey).Kinematics, ...
        kernelType,kernelScale,nonlinearL2,linearL2,holdOutNum, ...
        basisFxnNum(monkey).M1.maxDim,decodeDim);
    % PMd.
    output(monkey).PMd = prepForAnalysis(ShenoyMonkeyData(monkey).PMd, ...
        ShenoyMonkeyDataSingleTrial(monkey).PMd, ...
        ShenoyMonkeyData(monkey).Kinematics, ...
        ShenoyMonkeyDataSingleTrial(monkey).Kinematics, ...
        kernelType,kernelScale,nonlinearL2,linearL2,holdOutNum, ...
        basisFxnNum(monkey).PMd.maxDim,decodeDim);
    % pooled.
    output(monkey).pooled = prepForAnalysis( ...
        poolDatasets(ShenoyMonkeyData(monkey).M1, ...
        ShenoyMonkeyData(monkey).PMd), ...
        poolDatasets(ShenoyMonkeyDataSingleTrial(monkey).M1, ...
        ShenoyMonkeyDataSingleTrial(monkey).PMd), ...
        ShenoyMonkeyData(monkey).Kinematics, ...
        ShenoyMonkeyDataSingleTrial(monkey).Kinematics, ...
        kernelType,kernelScale,nonlinearL2,linearL2,holdOutNum, ...
        max([basisFxnNum(monkey).PMd.maxDim ...
        basisFxnNum(monkey).M1.maxDim]),decodeDim+10);
end

end

function output = prepForAnalysis(data,trialData,kin,trialKin,kernelType,kernelScale,nonLinearL2, ...
    linearL2,holdOutNum,factorNum,decodeDim)

% Prune out repeats.
data = pruneRepeats(data);
kin = pruneRepeats(kin);
trialData = pruneRepeatsTrial(trialData);
trialKin = pruneRepeatsTrial(trialKin);

% Perform linear mapping.
[output.data,output.linearPrediction.predicted] = ...
    predictKinUsingTBFandDataCondStructureSingletrial(kin,trialKin,holdOutNum, ...
    data,trialData,linearL2,factorNum);
% Get the variance explained.
output.linearPrediction.varExplained = getVarExplainedKinematics( ...
    output.data,output.linearPrediction.predicted);
% Get the variance explained after scrambling.
[~,null] = ...
    predictKinUsingTBFandDataCondStructureSingletrial(kin,trialKin,holdOutNum, ...
    data(randperm(size(data,2))),trialData(randperm(size(trialData,2))),linearL2,factorNum);
output.linearPrediction.nullVarExplained = getVarExplainedKinematics( ...
    output.data,null);
output.linearPrediction.pValPos = signrank( ...
    output.linearPrediction.nullVarExplained.pos.array, ...
    output.linearPrediction.varExplained.pos.array);
output.linearPrediction.pValVel = signrank( ...
    output.linearPrediction.nullVarExplained.vel.array, ...
    output.linearPrediction.varExplained.vel.array);
% Show the correlation structure.
[output.linearPrediction.correlations,output.linearPrediction.corrpVals,...
    ~,~] = studyAroundMeanParams(output.data,output.linearPrediction.predicted);

% Perform nonlinear mapping.
[~,output.nonlinearPrediction.predicted] = ...
    predictKinUsingTBFandDataCondStructureNonlinearSingleTrial(kin,trialKin,holdOutNum,data,trialData, ...
    kernelType,[kernelScale nonLinearL2 decodeDim],factorNum);
% Get the variance explained.
output.nonlinearPrediction.varExplained = getVarExplainedKinematics( ...
    output.data,output.nonlinearPrediction.predicted);
% Get the variance explained after scrambling.
[~,null] = ...
    predictKinUsingTBFandDataCondStructureNonlinearSingleTrial(kin,trialKin,holdOutNum, ...
    data(randperm(size(data,2))),trialData(randperm(size(trialData,2))), ...
    kernelType,[kernelScale nonLinearL2 decodeDim],factorNum);
output.nonlinearPrediction.nullVarExplained = getVarExplainedKinematics( ...
    output.data,null);
output.nonlinearPrediction.pValPos = signrank( ...
    output.nonlinearPrediction.nullVarExplained.pos.array, ...
    output.nonlinearPrediction.varExplained.pos.array);
output.nonlinearPrediction.pValVel = signrank( ...
    output.nonlinearPrediction.nullVarExplained.vel.array, ...
    output.nonlinearPrediction.varExplained.vel.array);
% Show the correlation structure.
[output.nonlinearPrediction.correlations,output.nonlinearPrediction.corrpVals,...
    ~,~] = studyAroundMeanParams(output.data,output.nonlinearPrediction.predicted);

end

